export const ADD_REPOSITORY_TO_FAVOURITE_CLICKED = "com.spykins.REPOSITORY_ADD_TO_FAVOURITE_CLICKED";
export const REMOVE_FROM_FAVOURITE_CLICKED = "com.spykins.REMOVE_FROM_FAVOURITE_CLICKED";
export const SEARCH_BUTTON_CLICKED = "com.spykins.SEARCH_BUTTON_CLICKED";
export const ON_TEXT_REMOVED = "com.spykins.ON_TEXT_REMOVED";
export const ON_NEW_REPOSITORY_FETCHED = "com.spykins.ON_NEW_REPOSITORY_FETCHED";
export const ON_FAVOURITE_IS_MORE_THAN_ONE = "com.spykins.ON_FAVOURITE_IS_MORE_THAN_ONE";
export const ON_SEARCH_BUTTON_CLICKED = "com.spykins.ON_SEARCH_BUTTON_CLICKED"
